name: pv-bff-local

services:
  backend:
    container_name: pv-backend-local
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST_DOCKER:-database}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./:/provoc
      - /provoc/node_modules
    extra_hosts:
      - "localapi.zembra.io:host-gateway"
    mem_limit: 768m
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: pv-database-local
    image: postgres:15.15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 512m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
