
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // process.env fallback so `prisma generate` succeeds on Railway at build
    // time when DATABASE_URL is not yet injected. The real URL is always
    // present at migrate / runtime.
    url: process.env.DATABASE_URL ?? "",
  },
});
