[build]
builder = "dockerfile"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
