sonar.projectKey=zembratech_pv-bff_87dce80b-c40c-4681-8334-1dacf13d8a91
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**, dist/**, **/*.module.ts, src/main.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.eslint.reportPaths=eslint-report.json